### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SOLBIKWEON** [nadavbra/fabric#1]
i use this code
`python3 set_maf_gene_effect_scores --reference-genome=GRCh38 --gene-dataset-dir=/usr/local/lib/python3.6/dist-packages/fabric/bin --maf-file=/home/dhlab/data/solbi/tcga_and_exac_analysis/gdc_somaticmutation_maf_BRCA_01A.tsv --effect-scores-output-csv file=/home/dhlab/data/solbi/tcga_and_exac_analysis/gdc_effect_scores.csv`

An error like this occurred in the code.
```
FABRIC|PID-13563 [2019-10-21 15:47:02.058672]: Will use 8 threads.
GENEFFECT|PID-13563 [2019-10-21 15:47:02.070033]: Working with reference genome version GRCh38 (user specified: GRCh38).
Traceback (most recent call last):
  File "set_maf_gene_effect_scores", line 45, in <module>
    setup = Setup(args.ref_genome, gene_dataset_dir = args.gene_dataset_dir, thread_pool = thread_pool, n_threads = n_threads)
  File "/home/dhlab/data/solbi/fabric_data/fabric/fabric/setup.py", line 23, in __init__
    self.geneffect_setup = geneffect.Setup(user_specified_ref_genome)
  File "/home/dhlab/.local/lib/python3.6/site-packages/geneffect/setup.py", line 14, in __init__
    self.genome_reader = GenomeReader(self._config_setup)
  File "/home/dhlab/.local/lib/python3.6/site-packages/geneffect/reference_genome.py", line 11, in __init__
    self.chromosome_readers = dict(map(self._create_chromosome_reader, os.listdir(self.ref_genome_dir)))
  File "/home/dhlab/.local/lib/python3.6/site-packages/geneffect/reference_genome.py", line 26, in _create_chromosome_reader
    return (chr_name, ChromosomeReader(f))
  File "/home/dhlab/.local/lib/python3.6/site-packages/geneffect/reference_genome.py", line 32, in __init__
    self.header_len = len(file_handler.readline())
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

How should I resolve this error?

**Comment by nadavbra** [comment]
Hi,

We are still working on Python3 support, but for now we support only Python2. Try to reinstall the packages with Python2. 

Best,
Nadav

**Comment by SOLBIKWEON** [comment]
thank you
but i have one more question.
An error like this occurred next.
what is problem?
```
FIRM|PID-30198 [2019-10-22 10:12:04.596682]: apply_scale.py failed using Cython, will use a (slower) pure-python implementation instead.
FABRIC|PID-30198 [2019-10-22 10:12:04.774569]: Will use 8 threads.
GENEFFECT|PID-30198 [2019-10-22 10:12:04.782521]: Working with reference genome version GRCh38 (user specified: GRCh38).
GENEFFECT|PID-30198 [2019-10-22 10:12:05.508703]: Loaded 93748 pfam records, 51710 of which are domains. Found 347 unique clans within these domains, 173 of which are common (with at least 25 occurrences).
GENEFFECT|PID-30198 [2019-10-22 10:13:11.022693]: Parsed 20365 UniProt records.
GENEFFECT|PID-30198 [2019-10-22 10:13:35.173182]: Loaded 2604486 gene annotations.
GENEFFECT|PID-30198 [2019-10-22 10:13:35.706361]: Loaded 20330 gene meta data records.
GENEFFECT|PID-30198 [2019-10-22 10:13:37.011000]: Constructed 708226 CDS records.
Traceback (most recent call last):
  File "set_maf_gene_effect_scores", line 45, in <module>
    setup = Setup(args.ref_genome, gene_dataset_dir = args.gene_dataset_dir, thread_pool = thread_pool, n_threads = n_threads)
  File "/home/dhlab/data/solbi/fabric_data/fabric/fabric/setup.py", line 16, in __init__
    self.geneffect_setup = geneffect.Setup(user_specified_ref_genome)
  File "/usr/local/lib/python2.7/dist-packages/geneffect/setup.py", line 23, in __init__
    self.genes = load_genes(self._config_setup, self.genome_reader, self.uniprot_records)
  File "/usr/local/lib/python2.7/dist-packages/geneffect/gene_data_loader.py", line 91, in load_genes
    append_if_not_none(genes, _parse_gene(uniprot_records[uniprot_id], uniprot_cds_rows, genome_reader))
  File "/usr/local/lib/python2.7/dist-packages/geneffect/gene_data_loader.py", line 99, in _parse_gene
    cds_rows.groupby('transcript_id')]
  File "/usr/local/lib/python2.7/dist-packages/geneffect/gene_data_loader.py", line 119, in _parse_cds_isoform
    return CDSIsoform(transcript_id, chromosome, strand, cds_coordinates, genome_reader)
  File "/usr/local/lib/python2.7/dist-packages/geneffect/gene_data_loader.py", line 41, in __init__
    self._set_cds_exons(cds_chromosomal_coordinates, genome_reader)
  File "/usr/local/lib/python2.7/dist-packages/geneffect/gene_data_loader.py", line 58, in _set_cds_exons
    cds_exon = CDSExon(self.chromosome, self.strand, chromosome_start, chromosome_end, last_isoform_end + 1, genome_reader)
  File "/usr/local/lib/python2.7/dist-packages/geneffect/gene_data_loader.py", line 78, in __init__
    self.seq = self.positive_strand_seq if strand == '+' else self.positive_strand_seq.reverse_complement()
  File "/home/dhlab/.local/lib/python2.7/site-packages/Bio/Seq.py", line 979, in reverse_complement
    return self.complement()[::-1]
  File "/home/dhlab/.local/lib/python2.7/site-packages/Bio/Seq.py", line 937, in complement
    raise ValueError("Mixed RNA/DNA found")
```

**Comment by nadavbra** [comment]
This is very strange. It looks like the reference genome you are using (GRCh38 in this case) has mixed RNA sequence in it (probably U nucleotides).
Have you set up geneffect with its configuration properly? Do you have access to the files of the correct reference genome?

**Comment by nadavbra** [comment]
Try to see you can use geneffect on its own (https://github.com/nadavbra/geneffect), before you try to use it in the context of FABRIC.
If the problem persists with geneffect, please open the issue on geneffect's repository (so all geneffect's users can benefit from the discussion).

**Comment by SOLBIKWEON** [comment]
Thanks solved the geneffect error.

I have something to ask you.
The sklearn and numpy version that causes such an error seems to be the problem.
Which sklearn and numpy version are you using in fabric?

this is my version
python : 2.7
sklearn : 0.18.1
numpy : 1.16.5

`/usr/local/lib/python2.7/dist-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
`

**Comment by nadavbra** [comment]
You're welcome.

Do you get any error? I see that you have warning, but I think it should be fine.

Anyway the versions I used at the time (for which it worked) were:
Python 2.7.15
numpy 1.16.0
sklearn 0.20.2

P.S. I am now in the midst of an effort to adapt fabric to Python 3, and to test it with all the newest versions of the packages (geneffect and firm have already been adapted). I expect to complete this within 1-2 weeks.

**Comment by SOLBIKWEON** [comment]
this is my error 
`
FIRM|PID-28486 [2019-11-01 08:37:13.933991]: apply_scale.py failed using Cython, will use a (slower) pure-python implementation instead.
FABRIC|PID-28486 [2019-11-01 08:37:14.049266]: Will use 8 threads.
GENEFFECT|PID-28486 [2019-11-01 08:37:14.056130]: Working with reference genome version GRCh38 (user specified: GRCh38).
GENEFFECT|PID-28486 [2019-11-01 08:37:14.753824]: Loaded 93748 pfam records, 51710 of which are domains. Found 347 unique clans within these domains, 173 of which are common (with at least 25 occurrences).
GENEFFECT|PID-28486 [2019-11-01 08:38:18.714559]: Parsed 20365 UniProt records.
GENEFFECT|PID-28486 [2019-11-01 08:38:42.873542]: Loaded 2604486 gene annotations.
GENEFFECT|PID-28486 [2019-11-01 08:38:43.402971]: Loaded 20330 gene meta data records.
GENEFFECT|PID-28486 [2019-11-01 08:38:44.706852]: Constructed 708226 CDS records.
/usr/local/lib/python2.7/dist-packages/Bio/Seq.py:2748: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  BiopythonWarning)
GENEFFECT|PID-28486 [2019-11-01 08:41:46.383590]: Parsed 18603 genes.
GENEFFECT|PID-28486 [2019-11-01 08:41:50.160949]: Finished setting up reference genome GRCh38.
/usr/local/lib/python2.7/dist-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
Traceback (most recent call last):
  File "set_maf_gene_effect_scores", line 45, in <module>
    setup = Setup(args.ref_genome, gene_dataset_dir = args.gene_dataset_dir, thread_pool = thread_pool, n_threads = n_threads)
  File "/home/dhlab/data/solbi/fabric_data/fabric/fabric/setup.py", line 19, in __init__
    self._set_gene_dataset(gene_dataset_dir)
  File "/home/dhlab/data/solbi/fabric_data/fabric/fabric/setup.py", line 30, in _set_gene_dataset
    self.gene_dataset = self._get_or_create_gene_dataset(gene_dataset_dir)
  File "/home/dhlab/data/solbi/fabric_data/fabric/fabric/setup.py", line 46, in _get_or_create_gene_dataset
    assert (gene_dataset['uniprot_id'] == pd.read_csv(gene_dataset_csv_file_path, index_col = 0)['uniprot_id']).all()
  File "/home/dhlab/.local/lib/python2.7/site-packages/pandas/core/ops.py", line 1676, in wrapper
    raise ValueError("Can only compare identically-labeled "
`
I haven't solved it yet.

That's is good new.  when you upload fabric to python 3, i will try.
first of all, i have to understand what the problems are.

**Comment by nadavbra** [comment]
What FABRIC command are you running?

**Comment by nadavbra** [comment]
It appears there's incompatibility between the genes parsed from geneffect to the genes you downloaded from the FTP site (for the pre-computed effect scores), probably because you use newer version of the various databases.
This is a bug in FABRIC I will need to solve (along with my efforts to support Python 3). Meanwhile, as a quick workaround, you can work with the data files found here: ftp://ftp.cs.huji.ac.il/users/nadavb/fabric_data/data/ (just replace them with the ones you have downloaded).

**Comment by SOLBIKWEON** [comment]
It's set again. and another error was occurred.
`
FIRM|PID-8165 [2019-11-04 10:16:23.985382]: apply_scale.py failed using Cython, will use a (slower) pure-python implementation instead.
FABRIC|PID-8165 [2019-11-04 10:16:24.167835]: Will use 8 threads.
GENEFFECT|PID-8165 [2019-11-04 10:16:24.175208]: Working with reference genome version GRCh38 (user specified: GRCh38).
GENEFFECT|PID-8165 [2019-11-04 10:16:24.889435]: Loaded 93748 pfam records, 51710 of which are domains. Found 347 unique clans within these domains, 173 of which are common (with at least 25 occurrences).
GENEFFECT|PID-8165 [2019-11-04 10:17:27.628275]: Parsed 20168 UniProt records.
GENEFFECT|PID-8165 [2019-11-04 10:17:51.748181]: Loaded 2604486 gene annotations.
GENEFFECT|PID-8165 [2019-11-04 10:17:52.267574]: Loaded 20080 gene meta data records.
GENEFFECT|PID-8165 [2019-11-04 10:17:53.588102]: Constructed 707004 CDS records.
/usr/local/lib/python2.7/dist-packages/Bio/Seq.py:2748: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  BiopythonWarning)
GENEFFECT|PID-8165 [2019-11-04 10:20:57.568950]: Parsed 18052 genes.
GENEFFECT|PID-8165 [2019-11-04 10:21:01.337918]: Finished setting up reference genome GRCh38.
/usr/local/lib/python2.7/dist-packages/sklearn/base.py:251: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.18.1 when using version 0.20.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/usr/local/lib/python2.7/dist-packages/sklearn/base.py:251: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.18.1 when using version 0.20.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/usr/local/lib/python2.7/dist-packages/sklearn/base.py:251: UserWarning: Trying to unpickle estimator VarianceThreshold from version 0.18.1 when using version 0.20.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
FABRIC|PID-8165 [2019-11-04 10:21:05.358700]: The 18052 genes in the created gene dataset are identical to the ones in the existing CSV file: /home/dhlab/data/solbi/fabric_data/genes_GRCh38.csv
FABRIC|PID-8165 [2019-11-04 10:21:05.387034]: Loaded 90590 MAF records.
Traceback (most recent call last):
  File "set_maf_gene_effect_scores", line 47, in <module>
    mutations = load_relevant_mutations(args.maf_file_path)
  File "/home/dhlab/data/solbi/fabric_data/fabric/fabric/maf_mutation_loader.py", line 12, in load_relevant_mutations
    relevant_mutations = all_mutations[all_mutations['Variant_Type'] == 'SNP']
  File "/home/dhlab/.local/lib/python2.7/site-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/dhlab/.local/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Variant_Type'
`

**Comment by SOLBIKWEON** [comment]
It's set again. and another error was occurred.
FIRM|PID-8165 [2019-11-04 10:16:23.985382]: apply_scale.py failed using Cython, will use a (slower) pure-python implementation instead. FABRIC|PID-8165 [2019-11-04 10:16:24.167835]: Will use 8 threads. GENEFFECT|PID-8165 [2019-11-04 10:16:24.175208]: Working with reference genome version GRCh38 (user specified: GRCh38). GENEFFECT|PID-8165 [2019-11-04 10:16:24.889435]: Loaded 93748 pfam records, 51710 of which are domains. Found 347 unique clans within these domains, 173 of which are common (with at least 25 occurrences). GENEFFECT|PID-8165 [2019-11-04 10:17:27.628275]: Parsed 20168 UniProt records. GENEFFECT|PID-8165 [2019-11-04 10:17:51.748181]: Loaded 2604486 gene annotations. GENEFFECT|PID-8165 [2019-11-04 10:17:52.267574]: Loaded 20080 gene meta data records. GENEFFECT|PID-8165 [2019-11-04 10:17:53.588102]: Constructed 707004 CDS records. /usr/local/lib/python2.7/dist-packages/Bio/Seq.py:2748: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future. BiopythonWarning) GENEFFECT|PID-8165 [2019-11-04 10:20:57.568950]: Parsed 18052 genes. GENEFFECT|PID-8165 [2019-11-04 10:21:01.337918]: Finished setting up reference genome GRCh38. /usr/local/lib/python2.7/dist-packages/sklearn/base.py:251: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.18.1 when using version 0.20.2. This might lead to breaking code or invalid results. Use at your own risk. UserWarning) /usr/local/lib/python2.7/dist-packages/sklearn/base.py:251: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.18.1 when using version 0.20.2. This might lead to breaking code or invalid results. Use at your own risk. UserWarning) /usr/local/lib/python2.7/dist-packages/sklearn/base.py:251: UserWarning: Trying to unpickle estimator VarianceThreshold from version 0.18.1 when using version 0.20.2. This might lead to breaking code or invalid results. Use at your own risk. UserWarning) FABRIC|PID-8165 [2019-11-04 10:21:05.358700]: The 18052 genes in the created gene dataset are identical to the ones in the existing CSV file: /home/dhlab/data/solbi/fabric_data/genes_GRCh38.csv FABRIC|PID-8165 [2019-11-04 10:21:05.387034]: Loaded 90590 MAF records. Traceback (most recent call last): File "set_maf_gene_effect_scores", line 47, in <module> mutations = load_relevant_mutations(args.maf_file_path) File "/home/dhlab/data/solbi/fabric_data/fabric/fabric/maf_mutation_loader.py", line 12, in load_relevant_mutations relevant_mutations = all_mutations[all_mutations['Variant_Type'] == 'SNP'] File "/home/dhlab/.local/lib/python2.7/site-packages/pandas/core/frame.py", line 2927, in __getitem__ indexer = self.columns.get_loc(key) File "/home/dhlab/.local/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc return self._engine.get_loc(self._maybe_cast_indexer(key)) File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item KeyError: 'Variant_Type'

**Comment by SOLBIKWEON** [comment]
thank you so much.
I get the results by fabric. finally
The analysis is based on the results.
We had loads of help from you.

when you upload fabric to python 3, i will try again

thanks
solbi

**Comment by nadavbra** [comment]
Sure thing, I'm glad I could help.
I will update when the current problems you pointed out to (including Python 3) are fixed.

**Comment by nadavbra** [comment]
Just to update that fabric should now work with Python 3.
