### ISSUE TITLE
result file was empty

### ISSUE THREAD

**Issue by SOLBIKWEON** [nadavbra/fabric#2]
hi
I run fabric with TCGA somatic mutation data.
and gained diff.csv, combined.csv and TCGA-project name's csv files.

but combined.csv file and TCGA-project name's csv files were empty.
what's wrong?

**Comment by nadavbra** [comment]
Did you run the analyze_maf_genes commands? Could you please provide the entire command lines you ran? Please also attach the outputs of your executions. 
When you say the files were empty, do you mean literally empty (i.e. size 0 bytes) or only with headers?

**Comment by nadavbra** [comment]
Has this worked out for you?

**Comment by SOLBIKWEON** [comment]
no
but I found cause of the error.
Its firm error. I didn't setting pfam HMM profiles.
I have to find a way to download hmm files. The error has not been resolved yet.

**Comment by nadavbra** [comment]
I realized that installing fabric was more complicated than I had appreciated.
To help you get started more easily, I created an automatic installation script that should take care of everything (installing fabric, firm and geneffect, and putting all the data files in place).

To use the script, just run:
```
wget https://raw.githubusercontent.com/nadavbra/fabric/master/install_fabric.sh
chmod a+x install_fabric.sh
./install_fabric.sh
```
